version: "3"
services:
  
  platform-mysql:
    restart: always
    container_name: platform-mysql
    command: 
     --lower_case_table_names=1
     --character-set-server=utf8mb4
     --collation-server=utf8mb4_general_ci
     --explicit_defaults_for_timestamp=true
    image: mysql:5.7.30
    environment:
     TZ: Asia/Shanghai
     MYSQL_ROOT_PASSWORD: 123456
    ports:
     - "0.0.0.0:38001:3306"
    volumes: 
     - ./data/mysql/db:/var/lib/mysql
     - ./data/mysql/conf/conf.d:/etc/mysql/conf.d

  platform-redis:
    image: redis:4.0-alpine
    container_name: platform-redis
    command: redis-server --requirepass 123456
    restart: always
    volumes:
      - ./data/redis/data:/data
      - ./data/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "0.0.0.0:38002:6379"

